export default {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_MOVIES: 'FETCH_MOVIES',
    FETCH_MOVIE: 'FETCH_MOVIE',
    SET_MOVIE: 'SET_MOVIE',
	POST_REVIEW: 'POST_REVIEW',
	PURCHASE_POSTED:'PURCHASE_POSTED',
	PURCHASE_RESET:'PURCHASE_RESET'
}